import random
import string

def generate_password(length, use_upper, use_lower, use_symbols, use_digits): #define function named generate_password which will take further inputs
    characters = ''  #it will create empty  string which will store the characters which will generate

    if use_upper:
        characters += string.ascii_uppercase
    if use_lower:
        characters += string.ascii_lowercase
    if use_symbols:
        characters += string.punctuation
    if use_digits:
        characters += string.digits

    if not characters or length < 1:
        return "Please choose length more than 0." #to handle error if user choses lenth than 1
    
    password = ''.join(random.choice(characters)for _ in range(length))
    return password
''' .join is used to join the generated random characters
 generated by random.choice and for _ in is used  to generated
 character in range in length'''

#Taking inputs from user

length = int(input("Enter password length: "))
use_upper = input("Should password contain upper case characters? (y/n): ") == 'y'
use_lower = input("Should password contain lower case characters? (y/n): ") == 'y'
use_symbol = input("Should password contain symbols (y/n): ") == 'y'
use_digit = input("Should password contain digits (y/n): ") == 'y'

# Generate password
result = generate_password(length, use_upper, use_lower, use_digit, use_symbol)
print("Generated password:", result)

